# Development Environment Configuration
catalog: dev_catalog
default_schema: silver
table_prefix: dev_

# Environment-specific settings
spark_config:
  spark.sql.adaptive.enabled: true
  spark.sql.adaptive.coalescePartitions.enabled: true

# Data quality thresholds
dq_thresholds:
  pass_rate_warning: 95.0
  pass_rate_critical: 90.0
  execution_time_warning_ms: 30000
  execution_time_critical_ms: 60000

# Notification settings
notifications:
  enabled: false
  channels: []