# Production Environment Configuration
catalog: main
default_schema: silver
table_prefix: ""

# Environment-specific settings
spark_config:
  spark.sql.adaptive.enabled: true
  spark.sql.adaptive.coalescePartitions.enabled: true
  spark.sql.adaptive.skewJoin.enabled: true
  spark.sql.adaptive.localShuffleReader.enabled: true

# Data quality thresholds
dq_thresholds:
  pass_rate_warning: 99.0
  pass_rate_critical: 98.0
  execution_time_warning_ms: 60000
  execution_time_critical_ms: 120000

# Notification settings
notifications:
  enabled: true
  channels: ["slack", "email", "pagerduty"]
  slack_channel: "#data-quality-alerts"
  email_recipients: ["data-team@company.com", "platform-team@company.com"]
  pagerduty_service: "data-quality-service"