# Production Environment Configuration
environment: prod

# Databricks Configuration
databricks:
  workspace_url: "https://prod-workspace.cloud.databricks.com"
  cluster_id: "prod-cluster-id"
  
# Data Quality Configuration
dq:
  default_engine: "soda"
  default_severity: "high"
  default_run_policy: "hard_fail"
  max_retries: 5
  retry_delay_seconds: 60
  
# Storage Configuration
storage:
  results_table: "prod_dq_results"
  metrics_table: "prod_dq_metrics"
  watermark_table: "prod_dq_watermarks"
  
# Logging Configuration
logging:
  level: "WARNING"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Notification Configuration
notifications:
  enabled: true
  slack_webhook: "https://hooks.slack.com/services/prod/webhook"
  email_recipients: ["dq-team@company.com", "data-engineering@company.com"]
