# Staging Environment Configuration
catalog: staging_catalog
default_schema: silver
table_prefix: staging_

# Environment-specific settings
spark_config:
  spark.sql.adaptive.enabled: true
  spark.sql.adaptive.coalescePartitions.enabled: true
  spark.sql.adaptive.skewJoin.enabled: true

# Data quality thresholds
dq_thresholds:
  pass_rate_warning: 98.0
  pass_rate_critical: 95.0
  execution_time_warning_ms: 45000
  execution_time_critical_ms: 90000

# Notification settings
notifications:
  enabled: true
  channels: ["slack"]
  slack_channel: "#data-quality-staging"